### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by azzaea** [TMiguelT/vue-cwl#1]
Hello there!

Thank you for putting the effort into this tool. I like to cite it in a comparative paper about workflow management systems that I'm working on, and was wondering how to do so. Would you kindly advise?

Thanks,
Azza

**Comment by TMiguelT** [comment]
Hi @azzaea. Thanks for your interest. I'm perfectly happy for you to cite this tool, and I've added a DOI link in the readme (10.5281/zenodo.3368161) that should make it easier to cite.

That said, if you're looking into this area, I suspect you should cite https://github.com/rabix/cwl-svg as well as/instead of mine, since it's the CWL visualisation library that mine uses internally. 

Let me know if you have any more questions.

**Comment by azzaea** [comment]
Excellent! Thank you for the prompt response and advise. Will cite cwl-svg too then

I'm closing this issue now, and thanks again.
